apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::079401129916:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-beJrFImtKUNe
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::079401129916:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2024-10-08T15:29:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1381"
  uid: dff954b3-bd61-402f-99bb-33083d8dfc38